version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/
  ais-sug-apiserver:
    depends_on:
      - database
    image: "ais-sug-apiserver:ver1"
    env_file:
      - database.env
    environment:
      POSTGRES_HOST: database
    ports:
      - 8080:8080

volumes:
  database-data:

