version: "3"
services:
  postgres:
    image: postgres:9.6.17-alpine
    env_file:
      - env_files/database.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  pgadmin:
    image: dpage/pgadmin4:4.20
    env_file:
      - env_files/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
  apiserver:
    depends_on:
      - postgres
    image: ais-sug-apiserver:ver1
    volumes:
      - ./config/ais-sug-back.yml:/config.yml
    ports:
      - 8080:8080

volumes:
  postgres-data:
  pgadmin-data:
